### ISSUE TITLE
Тестовое задание Уно-софт

### ISSUE THREAD

**Issue by mary-grigoriiva** [mgvts/spa_vk_api#1]
Добрый вечер, Владислав.
У отсортированных друзей должен отображаться также возраст и кол-во друзей.
При попытке удаления кого-либо из списка исходных друзей, значок крестика сильно проваливается за соседнюю форму 
![image](https://github.com/mgvts/spa_vk_api/assets/149430804/fc654bc5-bf69-4906-83e3-5e8f6b32854e)

**Comment by mgvts** [comment]
в связи с тем что есть существенные ограничения на [запросы](https://dev.vk.com/ru/api/api-requests#%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D0%BD%D1%8B%D0%B5%20%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D1%8F) и что метод [friends.get](https://dev.vk.com/ru/method/friends.get) не даёт напрямую ответ и приходится делать через [users.get](https://dev.vk.com/ru/method/users.get) тк только оттуда можно достать нужное [поле](https://dev.vk.com/ru/reference/objects/user#counters) причём даётся только при одном id изза этого метод делается крайне долго и ужасно неэффективно

**Comment by mary-grigoriiva** [comment]
Добрый день. Отображение возраста и кол-ва друзей - обязательные условия выполнения задания

**Comment by mgvts** [comment]
Добрый, хорошо, должно работать, проверяйте

**Comment by mary-grigoriiva** [comment]
Добрый день, проверила. Не у всех отображается количество друзей, хотя в профиле оно есть.

**Comment by mgvts** [comment]
> Добрый день, проверила. Не у всех отображается количество друзей, хотя в профиле оно есть.

ожидание подгрузки достаточно долгое из-за особенностей  vkapi, добавил интерактивное отслеживание подгруженного количества,
так же проблема могла быть если выбирать несколько профилей, тогда задержка была недостаточно большой, поправил
